<a href="https://colab.research.google.com/github/AzazelPazuzu/Intro/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

LISTS

In [4]:
my_list = [[1,2,3,4,5], [6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

NUMPY ARRAYS

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.16436619, 0.10537205, 0.50477589, 0.74974098],
       [0.41300834, 0.07188541, 0.1012641 , 0.78191547],
       [0.44732979, 0.89723709, 0.91842817, 0.77142496]])

In [6]:
np1.dtype

dtype('float64')

TENSORS

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 2.0700, -1.0838, -1.5057,  0.1338],
        [ 1.2213,  0.5710, -0.7451,  1.2199],
        [ 0.9037, -1.4021,  0.5140,  1.1555]])

In [14]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
##Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1644, 0.1054, 0.5048, 0.7497],
        [0.4130, 0.0719, 0.1013, 0.7819],
        [0.4473, 0.8972, 0.9184, 0.7714]], dtype=torch.float64)